site_name: Vanessa Automation
theme:
  name: material
  language: 'ru'
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.png'
  palette:
    primary: 'white'
    accent: 'red'
  features:
    - tabs
    - instant
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - ru
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pr-Mex/vanessa-automation
    - icon: fontawesome/brands/telegram
      link: https://t.me/VanessaAutomation
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
site_url: 'https://pr-mex.github.io/vanessa-automation'
repo_name: 'pr-mex/vanessa-automation'
repo_url: 'https://github.com/pr-mex/vanessa-automation'
edit_uri: 'edit/develop/docs'
